name: 'Pdcast Generator'
author: George
description: Docker Podcast Generator for GitHub Actions
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-branch'
  color: 'red'
inputs:
  email:
    description: The committer's email
    require: true
    default: ${{github.actor}}@localhost
  name:
    description: The committer's name
    required: true
    default: ${{github.actor}}